global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'gqlgateway-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gqlgateway-api:5050']
        labels:
          app: 'gqlgateway'
          environment: 'benchmark'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
